import JSZip from 'jszip';
import { jsPDF } from 'jspdf';
import { OxybottProject } from '../projects/projectStore';

/**
 * EXPORT FUNCTIONS
 */

// 1. Export as .ino file
export const exportAsIno = (project: OxybottProject) => {
  const filename = `${project.metadata.name.toLowerCase().replace(/\s+/g, '_')}.ino`;
  const blob = new Blob([project.generatedCode || '// Empty sketch\n'], { type: 'text/plain;charset=utf-8' });
  triggerDownload(blob, filename);
};

// 2. Export as Blockly JSON (.json)
export const exportAsBlocklyJson = (project: OxybottProject) => {
  const filename = `${project.metadata.name.toLowerCase().replace(/\s+/g, '_')}_workspace.json`;
  const jsonStr = JSON.stringify(project.workspaceJson || {}, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  triggerDownload(blob, filename);
};

// 3. Export as Oxybott Project (.oxy / .oxyproj)
export const exportAsOxyProject = (project: OxybottProject, ext: 'oxy' | 'oxyproj' = 'oxyproj') => {
  const filename = `${project.metadata.name.toLowerCase().replace(/\s+/g, '_')}.${ext}`;
  const jsonStr = JSON.stringify(project, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  triggerDownload(blob, filename);
};

// Backward compatibility alias
export const exportAsAceProject = exportAsOxyProject;

// 4. Export as ZIP Archive using JSZip
export const exportAsZip = async (project: OxybottProject) => {
  const zip = new JSZip();
  const safeName = project.metadata.name.toLowerCase().replace(/\s+/g, '_');

  // Add files to ZIP root
  zip.file(`${safeName}.ino`, project.generatedCode || '// Empty sketch\n');
  zip.file('workspace.json', JSON.stringify(project.workspaceJson || {}, null, 2));
  zip.file('metadata.json', JSON.stringify(project.metadata, null, 2));
  zip.file(
    'README.md',
    `# ${project.metadata.name}\n\nGenerated by **Oxybott Visual Studio**\n\n- **Target Board:** ${project.metadata.boardId}\n- **Created:** ${new Date(project.metadata.createdAt).toLocaleString()}\n\n## Arduino Source Code\n\`\`\`cpp\n${project.generatedCode}\n\`\`\`\n`
  );

  const zipContent = await zip.generateAsync({ type: 'blob' });
  triggerDownload(zipContent, `${safeName}_project.zip`);
};

// 5. Export as PDF Report using jsPDF
export const exportAsPdfReport = (project: OxybottProject) => {
  const doc = new jsPDF();
  const safeName = project.metadata.name;

  // Title Header
  doc.setFillColor(17, 24, 39); // #111827 Dark header
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(91, 228, 255); // Cyan accent
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('OXYBOTT VISUAL STUDIO', 14, 18);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Project Specification & Source Code Report', 14, 27);

  // Metadata Section
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Project: ${safeName}`, 14, 48);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Target Board: ${project.metadata.boardId.toUpperCase()}`, 14, 56);
  doc.text(`Generated Date: ${new Date().toLocaleString()}`, 14, 62);
  doc.text(`Project ID: ${project.metadata.id}`, 14, 68);

  // Line Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 74, 196, 74);

  // Code Section Title
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Generated C++ Source Code (main.ino):', 14, 84);

  // Code Block Box
  const codeLines = doc.splitTextToSize(project.generatedCode || '// Empty code', 170);
  let y = 92;

  doc.setFont('courier', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);

  codeLines.forEach((line: string, idx: number) => {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    const lineNum = String(idx + 1).padStart(3, ' ');
    doc.text(`${lineNum} | ${line}`, 14, y);
    y += 5;
  });

  doc.save(`${safeName.toLowerCase().replace(/\s+/g, '_')}_report.pdf`);
};

/**
 * IMPORT FUNCTION (Handles .ino, .zip, .json, .oxy, .oxyproj, .ace, .aceproj)
 */
export interface ImportedProjectData {
  name: string;
  boardId: string;
  workspaceJson: object;
  generatedCode: string;
}

export const importProjectFile = async (file: File): Promise<ImportedProjectData> => {
  const fileName = file.name.toLowerCase();

  // A) Handle .ino files
  if (fileName.endsWith('.ino')) {
    const text = await file.text();
    const name = file.name.replace(/\.ino$/i, '');
    return {
      name: capitalizeWords(name.replace(/_/g, ' ')),
      boardId: 'uno',
      workspaceJson: { blocks: { languageVersion: 0, blocks: [] } }, // Empty block canvas, code preserved
      generatedCode: text,
    };
  }

  // B) Handle .oxy, .oxyproj, .ace or .aceproj files
  if (
    fileName.endsWith('.oxy') ||
    fileName.endsWith('.oxyproj') ||
    fileName.endsWith('.ace') ||
    fileName.endsWith('.aceproj')
  ) {
    const text = await file.text();
    const parsed = JSON.parse(text);
    return {
      name: parsed.metadata?.name || 'Imported Oxybott Project',
      boardId: parsed.metadata?.boardId || 'uno',
      workspaceJson: parsed.workspaceJson || { blocks: { languageVersion: 0, blocks: [] } },
      generatedCode: parsed.generatedCode || '',
    };
  }

  // C) Handle Blockly JSON (.json)
  if (fileName.endsWith('.json') && !fileName.endsWith('.ace.json')) {
    const text = await file.text();
    const parsed = JSON.parse(text);

    // Check if it's an Oxybott full project JSON export
    if (parsed.metadata && parsed.workspaceJson) {
      return {
        name: parsed.metadata.name || 'Imported Project',
        boardId: parsed.metadata.boardId || 'uno',
        workspaceJson: parsed.workspaceJson,
        generatedCode: parsed.generatedCode || '',
      };
    }

    // Standard Blockly JSON
    return {
      name: file.name.replace(/\.json$/i, ''),
      boardId: 'uno',
      workspaceJson: parsed.blocks ? parsed : { blocks: { languageVersion: 0, blocks: [parsed] } },
      generatedCode: '// Imported from Blockly JSON\nvoid setup() {}\nvoid loop() {}\n',
    };
  }

  // D) Handle .zip archive using JSZip
  if (fileName.endsWith('.zip')) {
    const zip = await JSZip.loadAsync(file);

    let workspaceJson: object = { blocks: { languageVersion: 0, blocks: [] } };
    let generatedCode = '';
    let projectName = file.name.replace(/\.zip$/i, '');
    let boardId = 'uno';

    // 1. Read metadata.json if present
    const metaFile = zip.file('metadata.json');
    if (metaFile) {
      try {
        const metaText = await metaFile.async('text');
        const meta = JSON.parse(metaText);
        if (meta.name) projectName = meta.name;
        if (meta.boardId) boardId = meta.boardId;
      } catch (_) {}
    }

    // 2. Read workspace.json if present
    const wsFile = zip.file('workspace.json');
    if (wsFile) {
      try {
        const wsText = await wsFile.async('text');
        workspaceJson = JSON.parse(wsText);
      } catch (_) {}
    }

    // 3. Read .ino file if present
    const inoFiles = Object.keys(zip.files).filter((f) => f.endsWith('.ino'));
    if (inoFiles.length > 0) {
      const inoFile = zip.file(inoFiles[0]);
      if (inoFile) {
        generatedCode = await inoFile.async('text');
      }
    }

    return {
      name: capitalizeWords(projectName.replace(/_/g, ' ')),
      boardId,
      workspaceJson,
      generatedCode,
    };
  }

  throw new Error(`Unsupported file type: ${file.name}`);
};

/**
 * HELPER UTILITIES
 */
const triggerDownload = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};

const capitalizeWords = (str: string) => {
  return str.replace(/\b\w/g, (c) => c.toUpperCase());
};
