import { ProgramAST, StatementNode } from './types';
import { compilerRegistry } from './registry';

export class ArduinoCodeGenerator {
  public static generate(ast: ProgramAST): string {
    if (ast.rawBlocksCount === 0) {
      return '';
    }

    const lines: string[] = [];

    // Header comment
    lines.push('// Generated by Oxybott Visual Studio Compiler');
    lines.push('// Target Architecture: Arduino C++ (.ino)\n');

    // 1. Library #includes
    if (ast.includes.size > 0) {
      lines.push('// --- LIBRARIES ---');
      for (const inc of Array.from(ast.includes).sort()) {
        lines.push(inc);
      }
      lines.push('');
    }

    // 2. Global Variable & Object Declarations
    if (ast.globals.size > 0) {
      lines.push('// --- GLOBAL DECLARATIONS ---');
      for (const [_key, dec] of ast.globals.entries()) {
        lines.push(dec);
      }
      lines.push('');
    }

    // 3. Helper Functions before setup()
    if (ast.helperFunctions.length > 0) {
      lines.push('// --- HELPER FUNCTIONS ---');
      for (const fn of ast.helperFunctions) {
        lines.push(fn);
      }
      lines.push('');
    }

    // 4. setup() Function Body
    lines.push('void setup() {');

    // Deduplicated pinMode() statements
    if (ast.pinModes.size > 0) {
      for (const [pin, mode] of ast.pinModes.entries()) {
        lines.push(`  pinMode(${pin}, ${mode});`);
      }
    }

    // Custom setup statements
    if (ast.setupStatements.length > 0) {
      for (const node of ast.setupStatements) {
        const stmtCode = this.generateNodeCode(node);
        if (stmtCode) {
          lines.push(`  ${stmtCode.replace(/\n/g, '\n  ')}`);
        }
      }
    }

    lines.push('}\n');

    // 5. loop() Function Body
    lines.push('void loop() {');
    if (ast.loopStatements.length > 0) {
      for (const node of ast.loopStatements) {
        const stmtCode = this.generateNodeCode(node);
        if (stmtCode) {
          lines.push(`  ${stmtCode.replace(/\n/g, '\n  ')}`);
        }
      }
    } else {
      lines.push('  // Put your main loop code here, to run repeatedly:');
      lines.push('  delay(10);');
    }

    lines.push('}');

    return lines.join('\n');
  }

  private static generateNodeCode(node: StatementNode): string | null {
    const plugin = compilerRegistry.get(node.type);
    if (plugin?.generateStatement) {
      const dummyCtx = {} as any;
      return plugin.generateStatement(node, dummyCtx);
    }

    return node.codeSnippet || null;
  }
}
